name: pseudofinder
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.2
  - biopython=1.79
  - blast=2.12.0
  - diamond=2.0.14
  - pal2nal=14.1
  - paml=4.9
  - plotly=5.6.0
  - pandas=1.4.1
  - numpy=1.22.2
  - reportlab=3.5.68
  - hmmer=3.2.1
  - muscle=3.8.1551
  - prodigal=2.6.3
  - parallel=20190722